name: Send email

on: 
  schedule:
    - cron: '35/5 * * * *'  # Schedule to run every 5 minutes

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your desired Python version

    - name: Send Email
      run: python ./email.py

